version: '3'
services:
    cv:
      build:
        context: .
        dockerfile: Dockerfile
        target: release
      volumes:  
        - cv:/opt/app
    web:
      image: nginx:1.23-alpine
      ports: 
      - "8080:80"
      volumes:
        - cv:/opt/app
volumes: 
  cv:
    
      
      
    
